FROM almalinux:9
ENV COURSE="DevOps" \
    DURATION="100HRS" 
ARG INSTRUCTOR="DevenderReddyMusukula"
RUN echo "Hi, Course is: ${COURSE}, duration is:${DURATION}, instructor is:${INSTRUCTOR}"
CMD ["sleep", "1000"]